version: '3.9'
services:
  db:
    image: mysql:8.2.0
    # command: mysqld --default-authentication-plugin=mysql_native_pass
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - restapi-network
  rest-with-spring-boot-udemy:
    image: cristian19952/rest-api
    restart: always
    build: ./rest-api
    working_dir: /rest-api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8080:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - restapi-network
networks:
  restapi-network:
    driver: bridge